openapi: 3.0.3
info:
  title: 'SimpleTodoApp API'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /register:
    post:
      summary: 'Handle an incoming registration request.'
      operationId: handleAnIncomingRegistrationRequest
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Auth endpoints'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: otjopthgjfoyglhahz
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: aufderhar.olaf@example.com
                password:
                  type: string
                  description: ''
                  example: dolorem
              required:
                - name
                - email
                - password
      security: []
  /login:
    post:
      summary: 'Handle an incoming authentication request.'
      operationId: handleAnIncomingAuthenticationRequest
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Auth endpoints'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: eldon55@example.net
                password:
                  type: string
                  description: ''
                  example: VRR`fn
              required:
                - email
                - password
      security: []
  /logout:
    post:
      summary: 'Destroy an authenticated session.'
      operationId: destroyAnAuthenticatedSession
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Auth endpoints'
      security: []
  /api/v1/todos:
    get:
      summary: ''
      operationId: getApiV1Todos
      description: ''
      parameters:
        -
          in: header
          name: 'Sanctum Cookie'
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - 'Todos CRUD'
    post:
      summary: ''
      operationId: postApiV1Todos
      description: ''
      parameters:
        -
          in: header
          name: 'Sanctum Cookie'
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - 'Todos CRUD'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: 'Ipsa voluptatum minima ut.'
              required:
                - description
  '/api/v1/todos/{id}':
    put:
      summary: ''
      operationId: putApiV1TodosId
      description: ''
      parameters:
        -
          in: header
          name: 'Sanctum Cookie'
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - 'Todos CRUD'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: 'Non vel vero quae ut quam et.'
                completed:
                  type: boolean
                  description: ''
                  example: false
    delete:
      summary: ''
      operationId: deleteApiV1TodosId
      description: ''
      parameters:
        -
          in: header
          name: 'Sanctum Cookie'
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - 'Todos CRUD'
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the todo.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: 'Auth endpoints'
    description: ''
  -
    name: 'Todos CRUD'
    description: ''
components:
  securitySchemes:
    default:
      type: apiKey
      name: 'Sanctum Cookie'
      in: header
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
